run:
  timeout: 5m

linters:
  enable:
    - govet        # catches suspicious constructs the compiler misses
    - errcheck     # ensures errors aren't silently dropped
    - staticcheck  # comprehensive static analysis
    - gosimple     # suggests simpler code patterns
    - ineffassign  # catches assignments whose values are never used
    - unused       # finds unused code
    - gofmt        # enforces standard formatting
    - goimports    # enforces import grouping/ordering

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-blank: true  # catches `_ = someFunc()` error suppression

issues:
  exclude-rules:
    # Test files get a pass on some strict rules
    - path: "_test\\.go"
      linters:
        - errcheck